apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-js-deployment
  namespace: cicd-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-js
  template:
    metadata:
      labels:
        app: hello-js
    spec:
      containers:
      - name: hello-js-container
        image: srbhdockerhub1st/hello-js-app:latest
        ports:
        - containerPort: 80
